# Site settings
author: Cliff Crelin
title: My Software Engineering Journey 
header-img: img/home-bg.png
email: cliff.crelin@gmail.com
copyright_name: Cliff Crelin
description: > # this means to ignore newlines until "baseurl:"
  Journey 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CCrelin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
